//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.11
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bifrost_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub main_character_id: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bifrost_user_character::Entity")]
    BifrostUserCharacter,
    #[sea_orm(
        belongs_to = "super::eve_character::Entity",
        from = "Column::MainCharacterId",
        to = "super::eve_character::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EveCharacter,
}

impl Related<super::bifrost_user_character::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BifrostUserCharacter.def()
    }
}

impl Related<super::eve_character::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EveCharacter.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
