//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bifrost_user_character")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    #[sea_orm(unique)]
    pub character_id: i32,
    pub owner_hash: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bifrost_user::Entity",
        from = "Column::UserId",
        to = "super::bifrost_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    BifrostUser,
    #[sea_orm(
        belongs_to = "super::eve_character::Entity",
        from = "Column::CharacterId",
        to = "super::eve_character::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EveCharacter,
}

impl Related<super::bifrost_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BifrostUser.def()
    }
}

impl Related<super::eve_character::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EveCharacter.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
