//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bifrost_user_character_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub character_id: i32,
    pub new_user_id: i32,
    pub previous_user_id: i32,
    pub date_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bifrost_user::Entity",
        from = "Column::NewUserId",
        to = "super::bifrost_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    BifrostUser2,
    #[sea_orm(
        belongs_to = "super::bifrost_user::Entity",
        from = "Column::PreviousUserId",
        to = "super::bifrost_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    BifrostUser1,
    #[sea_orm(
        belongs_to = "super::eve_character::Entity",
        from = "Column::CharacterId",
        to = "super::eve_character::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EveCharacter,
}

impl Related<super::eve_character::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EveCharacter.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
