//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bifrost_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bifrost_user_character::Entity")]
    BifrostUserCharacter,
}

impl Related<super::bifrost_user_character::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BifrostUserCharacter.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
