//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "eve_character")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub character_id: i64,
    pub corporation_id: i32,
    pub faction_id: Option<i32>,
    pub birthday: DateTime,
    pub bloodline_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub gender: String,
    pub name: String,
    pub race_id: i64,
    #[sea_orm(column_type = "Double", nullable)]
    pub security_status: Option<f64>,
    pub title: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::bifrost_auth_user_character::Entity")]
    BifrostAuthUserCharacter,
    #[sea_orm(has_many = "super::bifrost_auth_user_character_history::Entity")]
    BifrostAuthUserCharacterHistory,
    #[sea_orm(
        belongs_to = "super::eve_corporation::Entity",
        from = "Column::CorporationId",
        to = "super::eve_corporation::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EveCorporation,
    #[sea_orm(
        belongs_to = "super::eve_faction::Entity",
        from = "Column::FactionId",
        to = "super::eve_faction::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EveFaction,
}

impl Related<super::bifrost_auth_user_character::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BifrostAuthUserCharacter.def()
    }
}

impl Related<super::bifrost_auth_user_character_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BifrostAuthUserCharacterHistory.def()
    }
}

impl Related<super::eve_corporation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EveCorporation.def()
    }
}

impl Related<super::eve_faction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EveFaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
