//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "eve_corporation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub corporation_id: i64,
    pub alliance_id: Option<i32>,
    pub faction_id: Option<i32>,
    pub ceo_id: i32,
    pub creator_id: i32,
    pub date_founded: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub home_station_id: i64,
    pub member_count: i32,
    pub name: String,
    pub shares: Option<i64>,
    pub tax_rate: i32,
    pub ticker: String,
    pub url: Option<String>,
    pub war_eligible: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::eve_alliance::Entity",
        from = "Column::AllianceId",
        to = "super::eve_alliance::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EveAlliance,
    #[sea_orm(
        belongs_to = "super::eve_character::Entity",
        from = "Column::CeoId",
        to = "super::eve_character::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EveCharacter2,
    #[sea_orm(
        belongs_to = "super::eve_character::Entity",
        from = "Column::CreatorId",
        to = "super::eve_character::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EveCharacter1,
    #[sea_orm(
        belongs_to = "super::eve_faction::Entity",
        from = "Column::FactionId",
        to = "super::eve_faction::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EveFaction,
}

impl Related<super::eve_alliance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EveAlliance.def()
    }
}

impl Related<super::eve_faction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EveFaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
