//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.11
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "eve_alliance")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub alliance_id: i64,
    pub faction_id: Option<i32>,
    pub creator_corporation_id: i64,
    pub executor_corporation_id: Option<i64>,
    pub creator_id: i64,
    pub date_founded: DateTime,
    pub name: String,
    pub ticker: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::eve_corporation::Entity")]
    EveCorporation,
    #[sea_orm(
        belongs_to = "super::eve_faction::Entity",
        from = "Column::FactionId",
        to = "super::eve_faction::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EveFaction,
}

impl Related<super::eve_corporation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EveCorporation.def()
    }
}

impl Related<super::eve_faction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EveFaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
